POST http://localhost:3001/exams/add
Content-Type: application/json

{
  "examId": "1234",
  "patientId": "5678",
  "keyFindings": "Some findings",
  "brixiaScores": "Scores",
  "imageURL": "http://example.com/image.jpg"
}

###
GET http://localhost:3001/exams

